abstract class AppLanguage {
  static const required = 'Required';
  static const jobs = 'Jobs';
  static const settings = 'Settings';
  static const savedJobs = 'Saved Jobs';
  static const email = 'Email';
  static const password = 'Password';
  static const confirmPassword = 'Confirm Password';
  static const signIn = 'Sign In';
  static const signUp = 'Sign Up';
  static const forgotPassword = 'Forgot Password?';
  static const resetPassword = 'Reset Password';
  static const cancel = 'Cancel';
  static const submit = 'Submit';
  static const fullName = 'Full Name';
  static const logout = 'Logout';
  static const selectTheme = 'Select Theme';
  static const light = 'Light';
  static const dark = 'Dark';
  static const system = 'System';
  static const dashboard = 'Dashboard';
  static const addNewJob = "Add New Job";
  static const department = "Department";
  static const organisation = "Organization";
  static const category = "Category";
  static const description = "Description";
  static const vacancies = "Vacancies";
  static const payLevel = "Pay Level";
}
