// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-iP1MCxT8vWwuArh1gUm1jjVB1f3wutY',
    appId: '1:946961624710:web:1488a9a0ff4516930c2b07',
    messagingSenderId: '946961624710',
    projectId: 'gov-scout',
    authDomain: 'gov-scout.firebaseapp.com',
    storageBucket: 'gov-scout.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0oGyBXMWinG-rIn4Kvn54_XlS2eJVo7I',
    appId: '1:946961624710:android:d47e3558d545b7020c2b07',
    messagingSenderId: '946961624710',
    projectId: 'gov-scout',
    storageBucket: 'gov-scout.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1yWBg265yPoIwe6FWnCpjcELzvE59ME8',
    appId: '1:946961624710:ios:93a8c2876576fb8c0c2b07',
    messagingSenderId: '946961624710',
    projectId: 'gov-scout',
    storageBucket: 'gov-scout.firebasestorage.app',
    iosBundleId: 'com.infinitycodeworks.govscout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1yWBg265yPoIwe6FWnCpjcELzvE59ME8',
    appId: '1:946961624710:ios:93a8c2876576fb8c0c2b07',
    messagingSenderId: '946961624710',
    projectId: 'gov-scout',
    storageBucket: 'gov-scout.firebasestorage.app',
    iosBundleId: 'com.infinitycodeworks.govscout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-iP1MCxT8vWwuArh1gUm1jjVB1f3wutY',
    appId: '1:946961624710:web:55e006205856e7150c2b07',
    messagingSenderId: '946961624710',
    projectId: 'gov-scout',
    authDomain: 'gov-scout.firebaseapp.com',
    storageBucket: 'gov-scout.firebasestorage.app',
  );
}